version: "3"
services:
    client:
      build: ./client
      expose:
        - 3000
      ports:
        - "3000:3000"
      container_name: todo-client
      stdin_open: true
      command: npm start